"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Orientation_1 = require("./Model/Orientation");
const Coordinates_1 = require("./Model/Coordinates");
const Planet_1 = require("./Model/Planet");
const Rover_1 = require("./Model/Rover");
const orient = new Orientation_1.Orientation(0);
const pos = new Coordinates_1.Coordinates(0, 0);
const plan = new Planet_1.Planet(100, 100);
const rover = new Rover_1.Rover(orient, pos, plan);
rover.turn(new Orientation_1.Orientation(90));
rover.move();
rover.setCommands([rover.move.bind(rover), rover.move.bind(rover), rover.move.bind(rover), rover.move.bind(rover)]);
rover.executeCommands();
